AllCops:
  NewCops: enable
  Exclude:
    - "bin/*"
    - "test/*"
    - "*.gemspec"
    - "Rakefile"
    - "Gemfile"

Layout/LineLength:
  Max: 96

Metrics/ClassLength:
  Max: 120

Style/AsciiComments:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/ExplicitBlockArgument:
  Enabled: false
